deploy/lib/createFunctions.js
docs/README.md
examples/multiple/handler.js
examples/multiple/handler.py
examples/multiple/package.json
examples/multiple/serverless.yml
examples/nodejs10/serverless.yml
shared/validate.js

Example : 
```
service:
name: scaleway-node10
provider:
name: scaleway
runtime: python3       # Default runtime
env:
test: test
scwToken: <token>
scwOrganization: <token>
plugins:
- serverless-scaleway-functions
package:
exclude:
- .gitignore
- .git/**
functions:
first:                # No runtime specified so the default runtime will be used (here: python3)
handler: handler.handle
env:
local: local
second:
runtime: node10     # Here you can specify a specific runtime
handler: handler.handle
env:
local: local
```

Adding the possibility to specify the runtime in the function block

---

deploy/lib/createFunctions.js
shared/api/index.js
shared/api/runtimes.js
shared/runtimes.js
tests/functions/functions.test.js

It is possible to list runtimes dynamically from API : https://developers.scaleway.com/en/products/functions/api/#get-f7de6a
This PR aims to retrieve those runtimes when creating a function, and validating the runtime. Also, if the runtime have a status different than `available`, a warning is printed with `status_message` field.

List runtimes dynamically from API

---

examples/go/README.md
examples/go/go.mod
examples/go/handler.go
examples/go/mypackage/go.mod
examples/go/mypackage/handler.go
examples/go/package.json
examples/go113/README.md
examples/go113/go.mod
examples/go113/go.sum
examples/go113/handler.go
examples/go113/mypackage/go.mod
examples/go113/mypackage/go.sum
examples/go113/mypackage/handler.go
examples/go113/package.json
examples/go113/serverless.yml

- move the golang and go113 example in go113 folder
- create a folder go (for Go >= 1.17) with an example

Documentation and example for Go >= 1.17

---

README.md
examples/python3/serverless.yml

This PR aims to add a minimal set of instructions for creating, deploying and invoking a function. To make the setup easier, it relies on reading the credentials from the `scw` configuration file (https://github.com/scaleway/serverless-scaleway-functions/pull/83).
I've updated the Python 3.10 example to require no explicit credentials from the user.

Add quick-start docs

---

deploy/lib/buildAndPushContainers.js
package-lock.json
package.json
tests/deploy/buildAndPushContainers.test.js

Before this PR, if the docker build command failed, but a previous build has succeeded, serverless deploy would deploy the previously built image instead of just throwing an error.
This PR aims to solve this by printing an error message and exiting if the build failed for some reason.
Fixes #99

Print an error message and exit if docker build failed

---

deploy/lib/buildAndPushContainers.js
shared/api/registry.js
tests/containers/containers_private_registry.test.js

If the container build depends on an image located in a private registry, we now authenticate against that registry (as long as the registry where the pulled image is located is the same as the registry where the resulting image is pushed).
For example, this works if both images are in `rg.fr-par.scw.cloud` for example, but not if the base image is in `rg.nl-ams.scw.cloud` and the container is in `fr-par` region (image will be pushed in `rg.fr-par.scw.cloud`).
If we want to support the previous use-case, we have no way but parsing the `Dockerfile` and look for base images, pull these images with the correct credentials (that the user should supply).
Fixes #98

During container build, authenticate to registry to pull private images

---

deploy/lib/createFunctions.js
shared/runtimes.js

Added some details to warn about EOL and EOS
Result in shell :  
```
Using credentials from system environment
Runtime undefined is in End Of Support. It is no longer possible to create a new function with this runtime; however, functions that already use it can still be updated.
Note : Node 17 reached end of security support 1st June 2022, please upgrade to Node 16 or Node 18
Runtime lifecycle doc : https://www.scaleway.com/en/docs/compute/functions/reference-content/functions-lifecycle/#available-runtimes
Creating function first...
Environment: darwin, node 16.14.0, framework 3.19.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Error: message : Node 17 reached end of security …
```

add more details to eol/eos runtimes

---

deploy/lib/createContainers.js
tests/containers/containers.test.js
tests/containers/containers_private_registry.test.js

When assigning to a container an image from an other source (for example the console) it will not be updated on `serverless deploy` command
So I added in updating parameter the registry image to ensure it's the one pushed by serverless framework.
Closes #111

ensure registry image priority is serverless framework

---

README.md

This lib is not required anymore for go runtimes

remove unsupported golang repository doc

---

package-lock.json
package.json

Move `js-yaml` from `devDependencies` to `dependencies`, as this is actually used in the library code and this triggers some package managers such as yarn v2+:
```
❯ yarn serverless deploy
Environment: darwin, node 18.10.0, framework 3.23.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Error: serverless-scaleway-functions tried to access js-yaml, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

fix: js-yaml is actually a dependency

---

README.md

Fixed some small typos in the readme file

docs(readme): fix small typos

---

examples/container-schedule/serverless.yml
examples/container/serverless.yml

Hello!
I got the following error when using the container example with the `timeout` value set:
```
→ sls deploy                                                                                                                                                                                         
...
Environment: linux, node 19.7.0, framework 3.16.0, plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issue
Error:
Error: proto: syntax error (line 1:183): unexpected token 20000
at manageError (<path>/node_modules/serverless-scaleway-functions/shared/api/utils.js:23:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Promise.all (index 0)
```
Searching a bit, I found …

set timeout in seconds in container examples

---

README.md
examples/go/README.md
examples/go/cmd/main.go
examples/go/go.mod
examples/go/go.sum
examples/python3/handler.py

- Readme
- Go example
- Python example

Local testing example

---

invoke/scalewayInvoke.js

Mentionned in https://github.com/scaleway/serverless-scaleway-functions/issues/147
The error returned by function calls on `serverless invoke` command was not readable because of the wrong type.
After toString conversion :  
```
serverless invoke --function testfunc
[...]
AxiosError: Request failed with status code 403%
```

Fix error type serverless invoke

---

.github/workflows/test.yml
examples/nodejs-schedule/handler.js

- Check formatting before running tests
- To better understand why GHA fail sometimes
- Ran GHA

ops: check formatting before tests

---

deploy/lib/buildAndPushContainers.js

If container's directory is empty, don't build and push an image. The image registry is used instead to deploy the container.
Fix bug.
Deployed locally two containers: one with directory, the other one only with registry image. It is assumed that a user will never use a directory and a registry image at the same time as stated on the readme guidelines.

fix: deploy container with registry image

---

deploy/lib/createFunctions.js
deploy/lib/deployFunctions.js
shared/api/functions.js
shared/constants.js
tests/utils/misc/index.js

- introduce a concurrency limit when creating/updating/deploying functions (max 5 functions deployed at a time)
- wait until a function is fully deployed before trying to deploy another one; we will still have 5 functions deploying at the same time
- refactor `deployEachFunction` method
- add more logging to know what's going on and which function is being deployed
When deploying many functions at the same time (e.g. 50 functions), we would receive a 429 error (rate limit) thrown by Scaleway API. To avoid this, do not run all API requests concurrently, but 1 by 1 (for creation because it's a fast operation) or 5 by 5 (for deployment, as this takes more time).
BTW, this is similar to how Terraform deploy resources (10 by 10), I'm not …

 fix(deploy): API rate-limiting when deploying many functions

---

CHANGELOG.md
README.md
examples/container-schedule/package.json
examples/container/package.json
examples/go/package.json
examples/multiple/package.json
examples/nodejs-es-modules/package.json
examples/nodejs-schedule/package.json
examples/nodejs/package.json
examples/php/package.json
examples/python3/package.json
examples/rust/package.json
examples/secrets/package.json
examples/typescript/package.json
logs/lib/getLogs.js
package-lock.json
package.json

Add a deprecation message when running "serverless logs" command. 
This follows the deprecation of `/logs` endpoint: https://github.com/scaleway/docs-content/pull/2715. We want to display a warning message here during 1 month, so people are not surprised when we are going to remove the command and `/logs` endpoint.
- created a dummy python function
- ran `serverless logs` command:

Add a deprecation message when running "serverless logs" command

---

docs/rust.md
examples/rust/Cargo.lock
examples/rust/Cargo.toml
examples/rust/serverless.yml
examples/rust/src/handler.rs

Update rust example
Rust 1.79 is available, whereas Rust 1.65 is end of support. So the example should be with rust 1.79.
Deployed the function and checked "Ferris says hello!" was returned when calling the function.

chore(examples): update rust example

---

.github/workflows/test.yml
docs/golang.md
docs/javascript.md
docs/secrets.md
examples/go/serverless.yml
examples/multiple/serverless.yml
examples/nodejs-es-modules/serverless.yml
examples/nodejs/serverless.yml
package-lock.json
tests/functions/functions.test.js

- Pinned Serverless Framework in CI to last release of v3.0.9
- Removed node16 from CI as it causes error when loading some `serverless` dependencies
- Bumped deprecated runtimes used in E2E tests 
- Fix E2E tests before new release :rocket: 
- E2E tests are passing :white_check_mark:

fix(ci): pin Serverless Framework version

---

README.md

- Fixed a small typo on the README
- Typo is misleading: we do not have a http `disabled` option, call will not be accepted by the API
- Docs changes :white_check_mark: 
Fixes https://github.com/scaleway/serverless-scaleway-functions/issues/208

docs(README): fix disabled http option is not available

---

README.md
deploy/lib/createContainers.js
deploy/lib/createFunctions.js
examples/nodejs/serverless.yml
package-lock.json
package.json

* Add support for `sandbox` parameter for functions/containers.
* Allow Serverless Framework users to update to Sandbox V2
* Update the example used in E2E with `sandbox: v2`
* Deployed a function with the `sandbox: v2` :white_check_mark:

feat(deploy): add sandbox

---

deploy/lib/createContainers.js
deploy/lib/createFunctions.js

- Sandbox param was missing when updating function/container
- This prevents users from changing the Sandbox of their existing functions :/
- Tested locally :white_check_mark:

fix(deployment): add sandbox param in update call

---

CHANGELOG.md
README.md
deploy/lib/createContainers.js
examples/container/serverless.yml

- Add support for `scalingOption`
- Bump version to 0.4.14
- Deprecate `maxConcurrency` by adding a small warning message
- Be feature complete with the API
- Tested on the container example :white_check_mark:

feat(container): add scalingOption + bump version to 0.4.14

---

.github/workflows/test.yml
README.md
package.json

feat(slsfw): use osls as alternative
